Repository gap-packages/recog, pull requests merged in 2019-07, with the labels that each got.

#73 FindHomDbPerm: Add link to genss package into description string of `StabilizerChain` method
  gap/perm.gi
Labels: SummerSchoolMGR, documentation

#74 Improve information on methods for giants
  gap/giant.gi
  gap/perm.gi
Labels: SummerSchoolMGR, documentation, enhancement

#70 Small testing fixes / improvements
  gap/base/recognition.gi
Labels: SummerSchoolMGR

#76 Add options and improve printing of tests
  gap/base/recognition.gi
  tst/quick/PermCycle.tst
Labels: SummerSchoolMGR

#79 Restructure test directories
  tst/broken/quick/MatDiagonal.tst
  tst/broken/quick/Sporadic.tst
  tst/broken/quick/bugfix.tst
  tst/broken/veryslow/ClassicalNatural.tst
  tst/testall.g
  tst/working/quick/MatDiagonal.tst
  tst/working/quick/MatReducible.tst
  tst/working/quick/MatSn.tst
  tst/working/quick/MatTrivial.tst
  tst/working/quick/PermDirProd.tst
  tst/working/quick/PermTrivial.tst
  tst/working/quick/ProjLowIndex.tst
  tst/working/quick/ProjLowIndex2.tst
  tst/working/quick/ProjNotAbsIrred.tst
  tst/working/quick/ProjReducible.tst
  tst/working/quick/ProjStabChain.tst
  tst/working/quick/ProjSubfield.tst
  tst/working/quick/ProjSubfield2.tst
  tst/working/quick/ProjSubfield3.tst
  tst/working/quick/ProjTensor.tst
  tst/working/quick/ProjTensorInduced.tst
  tst/working/quick/ProjTrivial.tst
  tst/working/quick/Sporadic.tst
  tst/working/quick/bugfix.tst
  tst/working/quick/mixed.tst
  tst/working/slow/MatAn.tst
  tst/working/slow/MatC3.tst
  tst/working/slow/MatC3_2.tst
  tst/working/slow/MatHSmax5.tst
  tst/working/slow/NonDeletedPermModuleRepOfSn.tst
  tst/working/slow/ProjC6.tst
  tst/working/slow/ProjDet.tst
  tst/working/slow/basic.tst
  tst/working/veryslow/ClassicalNatural.tst
  tst/working/veryslow/MatC6.tst
  tst/working/veryslow/MatFDPM.tst
Labels: SummerSchoolMGR

#81 Uniform treatment for Order, even in projective case
  doc/recognition.xml
  gap/almostsimple.gi
  gap/base/recognition.gd
  gap/base/recognition.gi
  gap/c3c5.gi
Labels: SummerSchoolMGR

#86 Doc: tag fail, false, true as keywords, rather than code
  doc/afterrecog.xml
  doc/recognition.xml
Labels: SummerSchoolMGR

#93 Recognition info record is component object, not positional object
  doc/recognition.xml
Labels: SummerSchoolMGR, documentation

#103 update required version of AutoDoc
  makedoc.g
Labels: SummerSchoolMGR

#106 Extend the bibliography
  contrib/akos/RecogniseAnSnOnFDPM.g
  doc/intro.xml
  doc/recog.bib
  gap/AnSnOnFDPM.gi
  gap/SnAnBB.gi
  gap/almostsimple.gi
  gap/c3c5.gi
  gap/c6.gi
  gap/classical.gi
  gap/classicalnatural.gi
  gap/d247.gi
  gap/giant.gi
  gap/slconstr.gi
  gap/snksetswrsr.gi
Labels: SummerSchoolMGR, documentation

#114 Move stray test file into tst/working/quick
  tst/working/quick/PermAllSubgroups.tst
Labels: SummerSchoolMGR, tests

#116 Remove some documentation compilation warnings
  doc/methods.xml
  doc/recog.bib
Labels: SummerSchoolMGR, documentation

#119 Add some broken tests which test many subgroups
  tst/broken/veryslow/MatM11MaxSubgroups.tst
  tst/broken/veryslow/PermSym8Subgroups.tst
Labels: SummerSchoolMGR

#115 In FindHomMethodsPerm.PcgsForBlocks subgens can never be fail
  gap/perm.gi
Labels: SummerSchoolMGR, bug, bug: wrong answer

#121 Make regen_doc.g usable without option -A for GAP
  makedoc.g
  regen_doc.g
Labels: SummerSchoolMGR, enhancement

#113 Improve findgensNmeth
  doc/recognition.xml
  gap/base/recognition.gi
Labels: SummerSchoolMGR, documentation, enhancement

#126 Make regen_doc.g more portable
  regen_doc.g
Labels: SummerSchoolMGR, bug

#108 Improve documentation of functions in code and manual
  gap/almostsimple.gi
  gap/base/recognition.gi
Labels: SummerSchoolMGR, documentation

#110 Improve documentation of SnkSetswrSr method
  gap/perm.gi
  gap/snksetswrsr.gi
Labels: SummerSchoolMGR, documentation

#112 Refactor CalcNiceGensHomNode
  gap/base/recognition.gi
Labels: SummerSchoolMGR, enhancement

#131 Improve documentation of functions in code and manual II
  gap/matrix.gi
  gap/perm.gi
Labels: SummerSchoolMGR, documentation

#130 Improve RECOG.DecomposeNilpotent
  gap/generic/KnownNilpotent.gi
Labels: enhancement

#136 Improve documentation of FindKernel methods
  doc/recognition.xml
Labels: documentation

#142 Simplify and speed up IsPowerOfPrime
  gap/classical.gi
Labels: enhancement, performance

#149 Make the documentation compile again: change a tag </P> -> <P/>
  doc/recognition.xml
Labels: documentation

#150 Fix documentation for and rename Perm.VeryFewPoints
  doc/afterrecog.xml
  gap/perm.gi
  tst/working/slow/basic.tst
Labels: documentation
