Repository gap-packages/recog, pull requests merged in 2020-12, with the labels that each got.

#227 Fix comment in tst/testclassicalnatural.g
  tst/testclassicalnatural.g
Labels: tests

#226 Disable Sporadic tests
  tst/working/quick/Sporadic.tst.off
Labels: tests

#192 Add test for LargeBasePrimitive
  tst/working/quick/PermLargeBasePrimitive.tst
Labels: tests

#198 Improve RandomElm, RandomElmOrd, GetElmOrd
  gap/base/recognition.gi
Labels: documentation, enhancement

#194 Check that permutation methods validate input
  gap/perm.gi
Labels: enhancement

#158 Improve referencing in documentation in some parts of perm.gi
  gap/perm.gi
Labels: documentation, question

#193 Improve LargeBasePrimitive
  gap/perm/largebase.gi
Labels: enhancement
